using FRIWOApp;
using FRIWOApp.Services.Interfaces;
using FRIWOApp.Services;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Syncfusion.Blazor;
using FRIWOApp.Models;
using Blazored.Toast;
var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("MzQ5NzUxOUAzMjM3MmUzMDJlMzBLT2xNdW1IaFFKeHJnNEVvZVJDUXl4Z2RKWXc3dUhmWUwxYW9zTjIxemN3PQ==");
builder.Services.AddScoped<IWorkInstructionService, WorkInstructionService>();
builder.Services.AddScoped<WorkInstruction>();
builder.Services.AddScoped<WorkInstructionService>();
builder.Services.AddSyncfusionBlazor();
builder.Services.AddMemoryCache();
builder.Services.AddBlazoredToast();
await builder.Build().RunAsync();
